import pickle

mydict = {'imergMDS': r'\imerg',
          'imergTimeVar': '',
          'imergTimeDim': 'BeginDate',
          'imergVar': 'HQprecipitation',
          'imergName': 'IMERG',
          'imergNameDateFormat': '%Y-%m-%d',
          'imergExtension': '.nc4',
          'imergLat': 'lat',
          'imergLon': 'lon',
          'gldasMDS': r'\gldas',
          'gldasTimeVar': 'time',
          'gldasTimeDim': 'begin_date',
          'gldasVar': 'Qsb_tavg',
          'gldasName': 'GLDAS_CLSM025_DA1_D.A',
          'gldasNameDateFormat': '%Y%m%d',
          'gldasExtension': '.022.nc4.nc',
          'gldasLat': 'lat',
          'gldasLon': 'lon',
          'fldasMDS': r'\fldas',
          'fldasTimeVar': '',
          'fldasTimeDim': '',
          'fldasVar': 'Qs_tavg',
          'fldasName': 'FLDAS_NOAH01_C_GL_M.A',
          'fldasNameDateFormat': '%Y%m%d',
          'fldasExtension': '.001.nc.nc',
          'fldasLat': 'lat',
          'fldasLon': 'lon',
          'tempsrhMDS': r'\tempsrh',
          'tempsrhTimeVar': 'time',
          'tempsrhTimeDim': 'reference_date',
          'tempsrhVar': 'TMP_2maboveground',
          'tempsrhName': '',
          'tempsrhNameDateFormat': '%Y%m%d',
          'tempsrhExtension': '_00_temps_RH.nc',
          'tempsrhLat': 'latitude',
          'tempsrhLon': 'longitude',
          'windMDS': r'\wind',
          'windTimeVar': 'time',
          'windTimeDim': 'reference_date',
          'windVar': 'UGRD_10maboveground',
          'windName': '',
          'windNameDateFormat': '%Y%m%d',
          'windExtension': '_00_wind.nc',
          'windLat': 'latitude',
          'windLon': 'longitude',
          'airsMDS': r'\airs',
          'airsTimeVar': '',
          'airsTimeDim': 'location.AscendingGridStartTimeUTC',
          'airsVar': 'SurfAirTemp_A',
          'airsName': 'AIRS.',
          'airsNameDateFormat': '%Y.%m.%d',
          'airsExtension': '.L3.RetStd_IR001.v6.0.31.1.G20204214331.hdf.ncml.nc',
          'airsLat': 'Latitude',
          'airsLon': 'Longitude',
          'current_FolderName': 'Lake_Atitlan',
          'current_ServiceType': 'MapServer',
          'logFileDir': r'Full path to the directory you would like to store log files',
          'current_AdminDirURL': 'The ArcGIS admin url usually ends with /arcgis/admin',
          'current_Username': 'ArcGIS user name',
          'current_Password': 'ArcGIS password',
          'extract_Folder': r'full path to the directory where you want to extract data from',
          'gdb':  r'full path to ur geodatabase',
          }
output = open('config.pkl', 'wb')
pickle.dump(mydict, output)
output.close()
